export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_RANDOM_BY_COUNTRY = 'GET_PRODUCTS_RANDOM_BY_COUNTRY';
export const GET_DETAILS = 'GET_DETAILS';
export const RESET_DETAILS = 'RESET_DETAILS';
export const GET_REVIEWS_BY_PRODUCT = 'GET_REVIEWS_BY_PRODUCT';
export const RESET_REVIEWS_BY_PRODUCT = 'RESET_REVIEWS_BY_PRODUCT';
export const GET_LEAKED_PRODUCTS = 'GET_LEAKED_PRODUCTS';
export const RESET_LEAKED_PRODUCTS = 'RESET_LEAKED_PRODUCTS';